### ISSUE TITLE
Feature - Support draft05, draft06

### ISSUE THREAD

**Issue by korzio** [korzio/djv#17]
- [x] Document required changes for draft-05 as a new issue
- [x] Document required changes for draft-06 as a new issue
- [x] Make a issue for implementing changes
- [x] Implement changes. Make tests work
- [x] Change description to support draft-06 in json-schema-benchmark

**Comment by handrews** [comment]
Draft-06 is out!

[Guide for core and validation](https://github.com/json-schema-org/json-schema-spec/wiki/FAQ:-draft-wright-json-schema%5B-validation%5D-01)
[Guide for hyper-schema](https://github.com/json-schema-org/json-schema-spec/wiki/FAQ:-draft-wright-json-schema-hyperschema-01)

**Comment by Anthropic** [comment]
@korzio if you support at least half the items from 5/6 I will start switching my lib over to support yours, promise :)

**Comment by korzio** [comment]
@Anthropic I have plans for it. I think I'll start working on it next month. Thx anyways

**Comment by korzio** [comment]
https://github.com/korzio/djv/issues/51
