### ISSUE TITLE
json-pointers appear to be irrelevant

### ISSUE THREAD

**Issue by gentlefox** [korzio/djv#57]
Add a schema by name:

    env.addSchema('test', jsonSchema);

Validate dataObj against entire schema:

    env.validate('test', dataObj);

Validate dataProperty of dataObj against json-pointer ref of schema:

    env.validate('test#/dataProperty', { dataProperty: dataObj.dataProperty });

But results as if this was called:

    env.validate('test', { dataProperty: dataObj.dataProperty });

Checking what is referenced via resolve:

    env.resolve('test');
    env.resolve('test#/dataProperty');

results in the identical output.

Single property validation against what should be the correct reference results in validating a partial object against the entire schema. This takes **djv** from being something lightweight and very useful, to being completely unusable.

**djv version**: 1.2.0 (root minified file)

**Comment by korzio** [comment]
Thanks @gentlefox I will look into it

**Comment by gentlefox** [comment]
Actually, not an issue.
It was a draft version mismatch. Sorry to waste your time.
Thanks for what you've created.
